import { createFileRoute, Link } from "@tanstack/react-router";
import { SiteShell } from "@/components/site-shell";

const caseStudies = {
  "ecommerce-platform": { number: "01", title: "E-Commerce Platform", category: "Full-stack product", year: "2025", overview: "A commerce platform that brings product discovery, checkout, operations and delivery into one dependable flow.", problem: "Customers were moving between disconnected tools while the team had no single view of an order after purchase.", goal: "Create a trustworthy buying experience and a clearer operational system for the people fulfilling it.", solution: "A responsive storefront paired with an operations workspace for products, orders, payments and delivery routes.", technology: "React · TypeScript · Node.js · PostgreSQL · API design", outcome: "A foundation that makes the path from product discovery to delivery visible, measurable and easier to improve." },
  "research-management": { number: "02", title: "University Research Management System", category: "Business system", year: "2025", overview: "A coordinated workspace for research projects, researchers, approvals and academic workflows.", problem: "Research information was spread across files and conversations, making status, ownership and approvals difficult to track.", goal: "Give departments a shared source of truth without adding complexity to an already busy academic process.", solution: "A role-aware system that organizes projects, people, milestones, documents and approval states in one calm interface.", technology: "TypeScript · React · PostgreSQL · Workflow design", outcome: "A clearer research lifecycle with less administrative friction and stronger visibility for every stakeholder." },
  "disaster-relief": { number: "03", title: "Disaster Relief Management System", category: "Civic technology", year: "2024", overview: "A response platform connecting relief requests, resources, volunteers and distribution teams.", problem: "During a response, urgent requests and available resources were difficult to reconcile quickly and accurately.", goal: "Help coordinators prioritize need, allocate resources and understand what has reached the ground.", solution: "A request-to-distribution workflow with structured records, status changes and role-specific views.", technology: "React · REST APIs · Data modeling · UX research", outcome: "A more legible operating picture for teams working under pressure and changing conditions." },
  "performance-dashboard": { number: "04", title: "Business Performance Dashboard", category: "Data product", year: "2024", overview: "A focused operating view for sales, revenue, customers, inventory and performance.", problem: "Important signals lived in separate reports, making it hard to see what needed attention now.", goal: "Turn scattered business data into a concise view that supports confident, timely decisions.", solution: "A hierarchy of key metrics, trends and drill-down views designed for weekly and daily operating rhythms.", technology: "React · Data visualization · API integration · Product analytics", outcome: "A dashboard that makes performance easier to scan, discuss and act on." },
  "portfolio-experience": { number: "05", title: "Portfolio Experience", category: "Digital experience", year: "2026", overview: "This portfolio, designed around the intersection of business, design and technology.", problem: "A short landing page could not communicate the range, depth or thinking behind the work.", goal: "Create an editorial portfolio that rewards exploration while staying calm, clear and useful.", solution: "A long-form experience with case studies, process, experiments, capabilities and direct contact paths.", technology: "React · TanStack Router · TypeScript · CSS", outcome: "A flexible home for the work and the thinking behind it, built to evolve alongside the practice." },
} as const;

export const Route = createFileRoute("/work/$slug")({ head: ({ params }) => ({ meta: [{ title: `${caseStudies[params.slug as keyof typeof caseStudies]?.title ?? "Project"} — SO.` }] }), component: CaseStudy });

function CaseStudy() {
  const { slug } = Route.useParams();
  const project = caseStudies[slug as keyof typeof caseStudies] ?? caseStudies["portfolio-experience"];
  return <SiteShell active="work" className="inner-page case-study-page"><div className="detail-back"><Link to="/work/">‹ &nbsp; Back to work</Link><span>{project.number} / 05</span></div><section className="case-study"><header className="case-hero"><p className="page-label">{project.category} · {project.year}</p><h1>{project.title}</h1><p className="case-overview">{project.overview}</p></header><div className="case-grid"><div><p className="page-label">The problem</p><p>{project.problem}</p></div><div><p className="page-label">The business goal</p><p>{project.goal}</p></div></div><div className="case-process"><p className="page-label">My approach</p><div>{["Research", "Requirements", "UX / Product Design", "Development", "Testing"].map((step, index) => <article key={step}><span>0{index + 1}</span><strong>{step}</strong><p>{index === 0 ? "Understand the people, context and opportunity." : index === 1 ? "Translate needs into a focused product model." : index === 2 ? "Make the important paths clear and usable." : index === 3 ? "Build the system with care for its future." : "Check the details against real-world use."}</p></article>)}</div></div><div className="case-solution"><p className="page-label">The solution</p><h2>{project.solution}</h2><div className="case-meta"><div><b>Technology</b><span>{project.technology}</span></div><div><b>Result / outcome</b><span>{project.outcome}</span></div></div></div></section></SiteShell>;
}